// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using ExceptionManagmentPortal.Models;
using Microsoft.Rest;

namespace ExceptionManagmentPortal
{
    public partial interface IExceptionManagmentPortalClient : IDisposable
    {
        /// <summary>
        /// The base URI of the service.
        /// </summary>
        Uri BaseUri
        {
            get; set; 
        }
        
        /// <summary>
        /// Credentials for authenticating with the service.
        /// </summary>
        ServiceClientCredentials Credentials
        {
            get; set; 
        }
        
        /// <param name='prescriberId'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<IList<CrmErrorResponse>>> GetErrorRecordWithOperationResponseAsync(string prescriberId, CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        
        /// <param name='collectionId'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<TaskIListDocument>> QueryforErrorRecordsWithOperationResponseAsync(string collectionId, CancellationToken cancellationToken = default(System.Threading.CancellationToken));
    }
}
